name: Webmention & Rebuild

on:
  workflow_run:
    workflows: ["Build & Deploy Jekyll Site"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  webmention-and-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Download the .jekyll-cache from Workflow A
      - name: Download .jekyll-cache
        uses: actions/download-artifact@v4
        with:
          name: jekyll-cache
          path: .jekyll-cache

      # Download the _site artifact from Workflow A
      - name: Download _site artifact
        uses: actions/download-artifact@v4
        with:
          name: site-artifact
          path: ./_site

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6'
          bundler-cache: true

      - name: Send webmentions
        run: bundle exec jekyll webmention
        env:
          JEKYLL_ENV: production

      - name: Rebuild site with updated webmentions
        run: bundle exec jekyll build --baseurl "/"
        env:
          JEKYLL_ENV: production

      - name: Upload rebuilt site artifact for Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site

      - name: Deploy updated site
        id: deployment
        uses: actions/deploy-pages@v4

